sudo: false

language: python

python:
- "2.7"
- "3.4"
- "pypy"

env:
- SQLA_VERSION=0.9
- SQLA_VERSION=1.0
- SQLA_VERSION=1.1
- SQLA_VERSION=dev

install:
- pip install tox-travis
- pip install codecov

script:
- tox

after_success:
- codecov
